### PR TITLE
Document karabo-data-validate

### PR DESCRIPTION
**Pull request by takluyver**
As requested by email, a documentation page about `karabo-data-validate`.

I also made a few fixes and improvements to the validation code while I was looking at it.

### CODE REVIEW

**Comment by fangohr** [comment]
I am happy with the documentation part of this.

**Comment by tmichela** [comment]
LGTM

**Comment by antarcticrainforest** [comment]
LGTM

**Comment by takluyver** [comment]
I'm guessing you meant to merge this rather than closing it?

**Comment by fangohr** [comment]
Probably. I have made that mistake before ...

**Pull request merged**
