### PR TITLE
Check whether cast is safe when reusing output for position_modules

### PR DESCRIPTION
**Pull request by zhujun98**
@takluyver @ebadkamil 

As discussed. I cannot find the test code for this part but I think it should be fine.

### CODE REVIEW

**Comment by takluyver** [comment]
I'm not sure that there's currently a test covering this particular branch. It would be good to have one, though, especially now that it allows different dtypes. See e.g. [test_agipd_geometry.py](https://github.com/European-XFEL/karabo_data/blob/master/karabo_data/tests/test_agipd_geometry.py).

I'd add a test which exercises the uint16 -> float32 conversion you want to use.

**Comment by zhujun98** [comment]
I added a few lines in `test_agipd_geometry.py` to cover both safe and unsafe cast.

**Comment by takluyver** [comment]
Thanks, this looks good. Do you want a quick release so you can use this feature in karaboFAI soon?

**Comment by zhujun98** [comment]
A quick release of 0.6.2 is appreciated. We would like to have this enhancement in the karaboFAI release 0.5.2 next Monday.

**Comment by takluyver** [comment]
OK, 0.6.2 is out now.

**Comment by ebadkamil** [comment]
Thanks

**Pull request merged**
