### PR TITLE
Use intersection of selected & available trains for get_array/get_series

### PR DESCRIPTION
**Pull request by takluyver**
Closes gh-101

### CODE REVIEW

**Comment by takluyver** [comment]
Looks like I've broken something else for pandas. At least our tests caught that one. I'll investigate tomorrow.

**Comment by takluyver** [comment]
I fixed the second problem, but I still want to add a test case for the first problem (described in #101) before we merge it.

@hjkirkwood I'm assuming you can use this branch for a little while to do what you need, but let us know if you need the fix merged into master sooner.

**Comment by takluyver** [comment]
I got round to adding the test I wanted on the plane, so this is ready for review now.

I also noticed some deprecation warnings from h5py, which were easy to fix, so I've done that in this PR.

**Comment by tmichela** [comment]
LGTM,

minor: would be nice to have a test that select a data source with missing `trainIds` (not containing data) for which other data sources have data.

**Comment by tmichela** [comment]
Ah, my bad, I did not get that the data-set creation would skip every second train,
LGTM!

**Comment by takluyver** [comment]
No problem, that's not at all obvious from the changes in this pull request.

**Pull request merged**
