### PR TITLE
Only include relevant files from .select() and .deselect()

### PR DESCRIPTION
**Pull request by takluyver**
This partly addresses #131: it should make it possible to combine proc detector data with raw data, by deselecting the detector sources in the raw data.

### CODE REVIEW

**Comment by takluyver** [comment]
In the older runs, as described in #131, only data files from the fast detectors ended up in proc, so combining raw & proc was useful. In more recent experiments I just found, it looks like the `DA` files from the data aggregators are also copied to proc, so maybe this isn't so important any more. But maybe those files are being copied as a workaround to make it easier to process the data from a run together.

**Comment by tmichela** [comment]
Are all `DA` files copied to proc? Because some detector data (10Hz, like Jungfrau, Epix, ...) are stored in `DA` files. So running calibration on those detector would copy also the specific `DA` file.

**Comment by takluyver** [comment]
I thought about that, but it looks like files with no detectors in are also getting copied. See e.g. `/gpfs/exfel/exp/SCS/201921/p002409/proc/r0102`

**Comment by tmichela** [comment]
This seems like the right thing to do anyway, regardless of what file is copied or not...
LGTM

**Pull request merged**
